
export const metadata = {
  title: 'Best blog ever',
    description: 'Generated by create next app',
    
}

export default function RootLayout({ children }) {
  return (
    <section>
    {children}
    </section>
  )
}
