export const metadata = {
  title: {
    template: "%s | Create Next App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <section>{children}</section>;
}
