export const generateMetadata = async ({ params }) => {
  const data = await fetch(
    "https://jsonplaceholder.typicode.com/posts/" + params.id
  );
  const post = await data.json();

  return {
    title: ` ${post.title}`,
    description: `Generated by create next app`,
    openGraph: {
      title: ` ${post.title}`,
      description: `Generated by create next app`,
      url: "https://www.url.ie/",
      type: "website",
      images: "https://via.placeholder.com/600/24f355",
    },
  };
};

export default function Blog() {
  return <div>Blog</div>;
}
